apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: story-weaver-backend
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      container:
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      minScale: 0
      maxScale: 1 